/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.imagenes;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Usuario
 */
public class InformeEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InformeEmpleado
     */
    public InformeEmpleado() {
        initComponents();
         setSize(1000,550); //Escogemos el tamaño inicial
        setLocationRelativeTo(null); // Para que se inicie en medio de mi ventana
        setTitle("Generar Informe del empleado");
        String cadenaTexto=" ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        TextField_Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        TextField_Apellido = new javax.swing.JTextField();
        dni = new javax.swing.JLabel();
        TextField_dni = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        TextField_Direccion = new javax.swing.JTextField();
        Edad = new javax.swing.JLabel();
        TextField_Edad = new javax.swing.JTextField();
        AñosExperiencia = new javax.swing.JLabel();
        TextField_AñosExperiencia = new javax.swing.JTextField();
        HorasTrabajadas = new javax.swing.JLabel();
        TextField_HorasTrabajadas = new javax.swing.JTextField();
        PagoPorHora = new javax.swing.JLabel();
        TextField_PagoPorHora = new javax.swing.JTextField();
        NdeHijos = new javax.swing.JLabel();
        TextField_NdeHijos = new javax.swing.JTextField();
        Boton_Procesar = new javax.swing.JButton();
        bOTON_lIMPIAR = new javax.swing.JButton();
        Boton_Volver = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        GuardarFichero = new javax.swing.JButton();
        TextoFinal = new javax.swing.JTextArea();
        Imagen_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setText("Nombre: ");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 70, 30));

        TextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(TextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 120, 30));

        Apellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Apellido.setText("Apellido");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));
        jPanel1.add(TextField_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 120, 30));

        dni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dni.setText("D.N.I.:");
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        TextField_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_dniActionPerformed(evt);
            }
        });
        jPanel1.add(TextField_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 120, 30));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Direccion.setText("Dirección: ");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));
        jPanel1.add(TextField_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 120, 30));

        Edad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Edad.setText("Edad:");
        jPanel1.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));
        jPanel1.add(TextField_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 120, -1));

        AñosExperiencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AñosExperiencia.setText("Años de Experiencia: ");
        jPanel1.add(AñosExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));
        jPanel1.add(TextField_AñosExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 130, 30));

        HorasTrabajadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HorasTrabajadas.setText("Horas trabajadas: ");
        jPanel1.add(HorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));
        jPanel1.add(TextField_HorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 130, 30));

        PagoPorHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PagoPorHora.setText("Pago por hora: ");
        jPanel1.add(PagoPorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, -1));
        jPanel1.add(TextField_PagoPorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 172, 130, 30));

        NdeHijos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NdeHijos.setText("Nº de hijos: ");
        jPanel1.add(NdeHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));
        jPanel1.add(TextField_NdeHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 130, 30));

        Boton_Procesar.setBackground(new java.awt.Color(204, 204, 255));
        Boton_Procesar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Boton_Procesar.setText("PROCESAR");
        Boton_Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ProcesarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 170, -1));

        bOTON_lIMPIAR.setBackground(new java.awt.Color(204, 204, 255));
        bOTON_lIMPIAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bOTON_lIMPIAR.setText("LIMPIAR");
        bOTON_lIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOTON_lIMPIARActionPerformed(evt);
            }
        });
        jPanel1.add(bOTON_lIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 170, -1));

        Boton_Volver.setBackground(new java.awt.Color(204, 204, 255));
        Boton_Volver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Boton_Volver.setText("VOLVER");
        Boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 170, -1));

        Boton_Salir.setBackground(new java.awt.Color(204, 0, 0));
        Boton_Salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 51));
        Boton_Salir.setText("SALIR");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 170, 50));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setText("Informe Empleado");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        GuardarFichero.setBackground(new java.awt.Color(255, 255, 0));
        GuardarFichero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        GuardarFichero.setText("Guardar Fichero");
        GuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarFicheroActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 290, 70));

        TextoFinal.setColumns(20);
        TextoFinal.setRows(5);
        jPanel1.add(TextoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 320, 250));

        Imagen_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/imagenes/keyboard-g19dcb8544_1280.jpg"))); // NOI18N
        jPanel1.add(Imagen_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NombreActionPerformed
        String cadenaTexto = "\n ";
    }//GEN-LAST:event_TextField_NombreActionPerformed

    private void TextField_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_dniActionPerformed
          String cadenaTexto = "\n ";
    }//GEN-LAST:event_TextField_dniActionPerformed

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
         int opcion = JOptionPane.showConfirmDialog(InformeEmpleado.this, "¿Estas seguro que quieres cerrar la aplicación?",
            "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverActionPerformed
       Portada p1 = new Portada();
       p1.setVisible(true);
       dispose();
    }//GEN-LAST:event_Boton_VolverActionPerformed


    
    private void Boton_ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ProcesarActionPerformed
       String apellido = TextField_Apellido.getText();
       String AñosExperiencia = TextField_AñosExperiencia.getText();
       String Direccion = TextField_Direccion.getText();
      String Edad = TextField_Edad.getText();
       String HorasTrabajadas = TextField_HorasTrabajadas.getText();
       String NdeHijos= TextField_NdeHijos.getText();
       String Nombre = TextField_Nombre.getText();
       String PagoPorHora = TextField_PagoPorHora.getText();
       String DNI = TextField_dni.getText();
       
       TextoFinal.append(DNI+"\n");
         TextoFinal.append(AñosExperiencia+"\n");
           TextoFinal.append(Direccion+"\n");
             TextoFinal.append(Edad+"\n");
               TextoFinal.append(HorasTrabajadas+"\n");
                 TextoFinal.append(NdeHijos+"\n");
                   TextoFinal.append(Nombre+"\n");
                     TextoFinal.append(PagoPorHora+"\n");
                       TextoFinal.append(apellido+"\n");
       
    }//GEN-LAST:event_Boton_ProcesarActionPerformed

    private void bOTON_lIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOTON_lIMPIARActionPerformed
        TextField_Apellido.setText("");
        TextField_AñosExperiencia.setText("");
        TextField_Direccion.setText("");
        TextField_Edad.setText("");
        TextField_HorasTrabajadas.setText("");
        TextField_NdeHijos.setText("");
        TextField_Nombre.setText("");
        TextField_PagoPorHora.setText("");
        TextField_dni.setText("");
        
    }//GEN-LAST:event_bOTON_lIMPIARActionPerformed

    private void GuardarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFicheroActionPerformed
   
        
        String textoAlerta = "\n\n\n\n\n\nPara guardar el documento, \nprimero deben de haberse procesado los datos.";
        if(!TextoFinal.getText().equals("") && !TextoFinal.getText().equals(textoAlerta)){
            String ruta = "";
            // Creamos un JFileChooser, es una ventana para seleccionar un fichero
            JFileChooser fileChooser = new JFileChooser();
            // Hacemos que aparezca un fichero por defecto
            fileChooser.setSelectedFile(new File("InformeEmpleado.txt"));
            // Cambiamos el título de la ventana
            fileChooser.setDialogTitle("Selecciona un fichero");
            // Mostramos la ventana de seleccionar el fichero
            int resultado = fileChooser.showSaveDialog(null);
            // Si se ha seleccionado un fichero, si se pulsa cancelar no se ejecuta
            if (resultado == JFileChooser.APPROVE_OPTION) {
                // Obtenemos la ruta del fichero
                ruta = fileChooser.getSelectedFile().getAbsolutePath();
                }
            try {
                File f = new File(ruta);
                FileWriter fw = new FileWriter(f);
                fw.write(TextoFinal.getText());
                fw.close();
            } catch (IOException e) {
                System.out.println("Error a la hora de guardar el informe. " + e);
            }   
        }else{
            TextoFinal.setText(textoAlerta);
        }
        
        
    //GEN-LAST:event_BotonGuardarActionPerformed
    }//GEN-LAST:event_GuardarFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeEmpleado();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel AñosExperiencia;
    private javax.swing.JButton Boton_Procesar;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Edad;
    private javax.swing.JButton GuardarFichero;
    private javax.swing.JLabel HorasTrabajadas;
    private javax.swing.JLabel Imagen_Fondo;
    private javax.swing.JLabel NdeHijos;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PagoPorHora;
    private javax.swing.JTextField TextField_Apellido;
    private javax.swing.JTextField TextField_AñosExperiencia;
    private javax.swing.JTextField TextField_Direccion;
    private javax.swing.JTextField TextField_Edad;
    private javax.swing.JTextField TextField_HorasTrabajadas;
    private javax.swing.JTextField TextField_NdeHijos;
    private javax.swing.JTextField TextField_Nombre;
    private javax.swing.JTextField TextField_PagoPorHora;
    private javax.swing.JTextField TextField_dni;
    private javax.swing.JTextArea TextoFinal;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton bOTON_lIMPIAR;
    private javax.swing.JLabel dni;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
