/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.imagenes;

import Interfaces.imagenes.Portada;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MostrarFichero extends javax.swing.JFrame {

    /**
     * Creates new form MostrarFichero
     */
    public MostrarFichero() {
        initComponents();
        this.setLocationRelativeTo(null);
                setSize(1000,480); //Escogemos el tamaño inicial

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        BotonMenu = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        TextoProcesado = new javax.swing.JTextArea();
        BotonLimpiar = new javax.swing.JButton();
        BotonProcesar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonMenu.setBackground(new java.awt.Color(204, 204, 255));
        BotonMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonMenu.setText("VOLVER");
        BotonMenu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 200, 40));

        BotonSalir.setBackground(new java.awt.Color(255, 0, 51));
        BotonSalir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 0));
        BotonSalir.setText("SALIR");
        BotonSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 200, 70));

        TextoProcesado.setEditable(false);
        TextoProcesado.setBackground(new java.awt.Color(255, 204, 255));
        TextoProcesado.setColumns(20);
        TextoProcesado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoProcesado.setForeground(new java.awt.Color(0, 153, 153));
        TextoProcesado.setRows(5);
        PanelPrincipal.add(TextoProcesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 570, 280));

        BotonLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        BotonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonLimpiar.setText("LIMPIAR");
        BotonLimpiar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 200, 40));

        BotonProcesar.setBackground(new java.awt.Color(204, 204, 255));
        BotonProcesar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonProcesar.setText("MOSTRAR");
        BotonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProcesarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MOSTRAR FICHERO");
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 310, 60));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/imagenes/computer-workstation-g3950cbb7a_1280.jpg"))); // NOI18N
        PanelPrincipal.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1010, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        this.setVisible(false);
        Portada p1 = new Portada();
        p1.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(MostrarFichero.this, "¿Estas seguro que quieres cerrar la aplicación?",
            "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed

        TextoProcesado.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProcesarActionPerformed
        
        String ruta = "";
        String cadena = "";
        // Creamos un JFileChooser, es una ventana para seleccionar un fichero
        JFileChooser fileChooser = new JFileChooser();
        // Hacemos que aparezca un fichero por defecto
        fileChooser.setSelectedFile(new File("FicheroAMostrar.txt"));
        // Cambiamos el título de la ventana
        fileChooser.setDialogTitle("Selecciona un fichero");
        // Mostramos la ventana de seleccionar el fichero
        int resultado = fileChooser.showSaveDialog(null);
        // Si se ha seleccionado un fichero, si se pulsa cancelar no se ejecuta
        if (resultado == JFileChooser.APPROVE_OPTION)
        {
        // Obtenemos la ruta del fichero
        ruta = fileChooser.getSelectedFile().getAbsolutePath();
        }
        try {
            File f = new File(ruta);
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            while((linea=br.readLine())!= null){
                cadena += linea+"\n";
            }
            TextoProcesado.setText(cadena);
            fr.close();
            br.close();
        } catch (IOException e) {
            System.out.println("Error a la hora de guardar el recibo. " + e);
        }
    }//GEN-LAST:event_BotonProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarFichero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonProcesar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTextArea TextoProcesado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
