/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.imagenes;

import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Portada extends javax.swing.JFrame {

    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();
        setSize(1000,480); //Escogemos el tamaño inicial
        setLocationRelativeTo(null); // Para que se inicie en medio de mi ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        InformeEmpleado = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        Recibo = new javax.swing.JButton();
        Abrir_Fichero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InformeEmpleado.setBackground(new java.awt.Color(102, 153, 255));
        InformeEmpleado.setText("INFORME EMPLEADO");
        InformeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(InformeEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, 40));

        salir.setBackground(new java.awt.Color(153, 0, 0));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel3.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 60));

        Recibo.setBackground(new java.awt.Color(102, 153, 255));
        Recibo.setText("RECIBO");
        Recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciboActionPerformed(evt);
            }
        });
        jPanel3.add(Recibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 140, 40));

        Abrir_Fichero.setBackground(new java.awt.Color(51, 153, 255));
        Abrir_Fichero.setText("ABRIR FICHERO");
        Abrir_Fichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir_FicheroActionPerformed(evt);
            }
        });
        jPanel3.add(Abrir_Fichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/imagenes/portadaImagen.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InformeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeEmpleadoActionPerformed
        InformeEmpleado IE = new InformeEmpleado();
        IE.setVisible(true);
        dispose(); //para evitar abrir muchas ventanas
    }//GEN-LAST:event_InformeEmpleadoActionPerformed

    private void ReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReciboActionPerformed
        EmpleadoRecibo ER = new EmpleadoRecibo();
        ER.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReciboActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
 int opcion = JOptionPane.showConfirmDialog(Portada.this, "¿Estas seguro que quieres cerrar la aplicación?",
            "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            dispose();
        }
            
    }//GEN-LAST:event_salirActionPerformed

    private void Abrir_FicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir_FicheroActionPerformed
        MostrarFichero MF = new MostrarFichero();
        MF.setVisible(true);
        dispose();
    }//GEN-LAST:event_Abrir_FicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir_Fichero;
    private javax.swing.JButton InformeEmpleado;
    private javax.swing.JButton Recibo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
